"""Add users table for authentication

Revision ID: ab9ca7c0df3d
Revises: 20250110_add_pool_metadata
Create Date: 2025-10-14 10:52:45.087637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9ca7c0df3d'
down_revision = '20250110_add_pool_metadata'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index('idx_token_scores_smoothed', table_name='token_scores')
    op.drop_index('idx_token_scores_token_created', table_name='token_scores')
    op.create_index(op.f('ix_token_scores_created_at'), 'token_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_scores_smoothed_score'), 'token_scores', ['smoothed_score'], unique=False)
    op.drop_index('idx_tokens_liquidity', table_name='tokens')
    op.drop_index('idx_tokens_primary_dex', table_name='tokens')
    op.create_index(op.f('ix_tokens_created_at'), 'tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_tokens_liquidity_usd'), 'tokens', ['liquidity_usd'], unique=False)
    op.create_index(op.f('ix_tokens_mint_address'), 'tokens', ['mint_address'], unique=True)
    op.create_index(op.f('ix_tokens_status'), 'tokens', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_status'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_mint_address'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_liquidity_usd'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_created_at'), table_name='tokens')
    op.create_index('idx_tokens_primary_dex', 'tokens', ['primary_dex'], unique=False)
    op.create_index('idx_tokens_liquidity', 'tokens', ['liquidity_usd'], unique=False)
    op.drop_index(op.f('ix_token_scores_smoothed_score'), table_name='token_scores')
    op.drop_index(op.f('ix_token_scores_created_at'), table_name='token_scores')
    op.create_index('idx_token_scores_token_created', 'token_scores', ['token_id', 'created_at'], unique=False)
    op.create_index('idx_token_scores_smoothed', 'token_scores', ['smoothed_score'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
